
account_id = 'dda83bc45ee23dd747a7fe8c06c8edd4'
name = 'hello'
main = '.target/worker.js'
compatibility_date = '2023-10-30'

[site]

bucket = 'public'

[[d1_databases]]

binding = 'DB'
database_name = 'hello'
database_id = '0deb653d-3917-4aca-af57-00667007f0e0'

[[r2_buckets]]

binding = 'BUCKET'
bucket_name = 'hello'
